import Head from "next/head";

import AppWrapper from "@/components/AppWrapper";
import Login from "@/components/HomePage/Login";
import Dashboard from "@/components/HomePage/Dashboard";

import { useAuth } from "@/context/AuthContext";

export default function Home() {
    const { currentUser } = useAuth();
    console.log(currentUser);
    return (
        <>
            <Head>
                <title>TODOs App</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <AppWrapper>{!currentUser ? <Login /> : <Dashboard />}</AppWrapper>
        </>
    );
}
